### PR TITLE
make pep8 compulsory

### PR DESCRIPTION
**Pull request by Gustry**

### CODE REVIEW

**Comment by Gustry** [comment]
Sorry ? You mean because the test is executed on the 8 builds?

**Comment by timlinux** [comment]
No I mean because I added make pep8 to the travis build here:

https://github.com/kartoza/osm-reporter/blob/develop/.travis.yml#L90

(so you can remove my travis test in favour of your nicer one)

**Comment by Gustry** [comment]
Ah ok, understood. As you want, in inasafe repo, we still have both. One is making travis is failing and the other one is for the display.

**Comment by timlinux** [comment]
Ah ok I didn't realize we need both...leave it so then :-)

**Comment by timlinux** [comment]
Ah I wish this was merged before @dimasciput merged his stuff - we would have caught his PEP8 violations :-P

**Comment by timlinux** [comment]
I merged this as part of #109

**Pull request closed without merging**
