### PR TITLE
handle the timeout from overpass

### PR DESCRIPTION
**Pull request by Gustry**

### CODE REVIEW

**Comment by timlinux** [comment]
LGTM (once tests are passing)

**Comment by Gustry** [comment]
Thanks. I'm going to merge, tests have never passed on travis before. We should maybe disable it or fix it.

**Comment by timlinux** [comment]
Thanks @Gustry 

Are you still able to run tests ok on your local machine?

**Comment by Gustry** [comment]
Yes, there is a docker command for that in the Makefile. It works well.

**Pull request merged**
