### PR TITLE
Add date range inputs

### LINKED ISSUE #70: Add more user inputs to report, for example date range
Date range would help when an area was mapped in one year and then updated in another year by a different team of people. It would allow reporting only on the current "round" of data collection.

### PR DESCRIPTION
**Pull request by dimasciput**
Fix #70

- Update old js libraries
- Add date range inputs
- Use diff to query overpass with date range (http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Delta_between_two_dates_.28.22diff.22.29) 

### Gif
osm

### CODE REVIEW

**Comment by Gustry** [comment]
Thanks Dimas for the quick patch!
Looks good to me.

Just some questions: 
* Does it work or what happen if we set only *one* date? Is it from the date specified to today if we set only the first one for instance?
* For the user experience, I'm just thinking if we can have only one "refresh" button. You either move these date pickers to the map canvas next to the layer one, or you move the layer one. And then we will have one button less.

**Comment by timlinux** [comment]
Yeah maybe moving the feature type combo down to a row with the date pickers and then remove its refresh icon.

**Comment by dimasciput** [comment]
@Gustry @timlinux thanks for the feedbacks

I move the feature type selection to a row with date picker, also add a test.

osm

**Comment by timlinux** [comment]
LGTM thanks!

**Comment by Gustry** [comment]
Thanks @dimasciput !
I will deploy on staging

**Pull request merged**
